### ISSUE TITLE
/cui items, not working after adding a lot of items, Array Out of Bound

### ISSUE THREAD

**Issue by xcibe95x** [jojodmo/CustomItems#7]
After a certain amount of items running /cui items doesn't work properly and return this error in console

[15:43:15 WARN]: java.lang.ArrayIndexOutOfBoundsException: 9
[15:43:15 WARN]:        at java.util.Arrays$ArrayList.set(Unknown Source)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.NonNullList.set(SourceFile:53)
[15:43:15 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:108)
[15:43:15 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory.setItem(CraftInventory.java:99)
[15:43:15 WARN]:        at com.jojodmo.customitems.item.custom.CustomItemListInventory.addItem(CustomItemListInventory.java:122)
[15:43:15 WARN]:        at com.jojodmo.customitems.item.custom.CustomItemListInventory.lambda$createInventory$28(CustomItemListInventory.java:160)
[15:43:15 WARN]:        at java.util.HashMap.forEach(Unknown Source)
[15:43:15 WARN]:        at com.jojodmo.customitems.item.custom.CustomItemListInventory.createInventory(CustomItemListInventory.java:160)
[15:43:15 WARN]:        at com.jojodmo.customitems.item.custom.CustomItemListInventory.open(CustomItemListInventory.java:91)
[15:43:15 WARN]:        at com.jojodmo.customitems.item.custom.CustomItemListInventory.open(CustomItemListInventory.java:70)
[15:43:15 WARN]:        at com.jojodmo.customitems.item.custom.CustomItemCategoryInventory.open(CustomItemCategoryInventory.java:111)
[15:43:15 WARN]:        at com.jojodmo.customitems.command.CommandHandler.list(CommandHandler.java:183)
[15:43:15 WARN]:        at com.jojodmo.customitems.command.CommandType.run(CommandType.java:64)
[15:43:15 WARN]:        at com.jojodmo.customitems.command.CommandType.run(CommandType.java:48)
[15:43:15 WARN]:        at com.jojodmo.customitems.command.CommandHandler.onCommand(CommandHandler.java:107)
[15:43:15 WARN]:        at com.jojodmo.customitems.Main.onCommand(Main.java:216)
[15:43:15 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:43:15 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[15:43:15 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)
[15:43:15 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)
[15:43:15 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:43:22 INFO]: Size: 9. Unadded: 0. Broke: 0. Max:45
[15:43:22 WARN]: java.lang.ArrayIndexOutOfBoundsException

**Comment by jojodmo** [comment]
This bug should be fixed in the latest version of Custom Items! If you experience this issue again, please open another ticket or send a message on the discord!
